### ISSUE TITLE
Drache netzwerkfähig machen

### ISSUE THREAD

**Issue by Marcel-Mayer** [HftStuttgartSP2/DungeonArena#111]

**Comment by VolkanKutlar** [comment]
Drachenbewegung jetzt synchron. Animationen und sonstiges erst netzwerkfähig, wenn Basisimplementierung vorhanden.

**Comment by VolkanKutlar** [comment]
Alle Animationen synchron. Anpassungen notwendig wenn neue Features oder Animationen dazu kommen.
