### ISSUE TITLE
Feuerball vom Drachen immer nach Links.

### ISSUE THREAD

**Issue by Nitrodex** [HftStuttgartSP2/DungeonArena#279]

**Comment by VolkanKutlar** [comment]
Getestet und der Fehler kam nicht auf. Der Feuerball scheint bei allen Spielern synchron zu sein. Bitte nochmal testen.

**Comment by VolkanKutlar** [comment]
Nach weiterem Testen kam der Fehler dann auf, wenn der Drache ein CLient ist. Ist der Drache der Server, kommt kein Fehler auf. Es scheint so als ob die Clients nicht in der Lange währen Befehle an den Server zu senden.

**Comment by VolkanKutlar** [comment]
Änliches Problem wie hier:  Networking-Kommunikation: Bewegung-Animationen nicht networkingfähig #63 

Problem gelöst durch callback für Drachenrichtung. Die Richtung des Drachen wurde nicht richtig synchronisiert.
