### ISSUE TITLE
Player spawnen alle am gleichen Fleck und verschwinden dann

### ISSUE THREAD

**Issue by Nitrodex** [HftStuttgartSP2/DungeonArena#284]
Zu Beginn der Runde befinden sich alle Player an der selben Stelle und werden dann zu ihren eigentlichen Plätzen "gewarpt".
Liegt evtl an der Kamera.
Ähnliches Problem mit dem Warp-Feld.

**Comment by VolkanKutlar** [comment]
Bitte einmal prüfen an welchen Koordinaten bzw. an welcher Position die Spieler sich als erstes befinden.

Wenn sie grundsätzlich immer an der Stelle (0|0) sind, wird der bug sehr schwer zu fixen sein.

**Comment by Nitrodex** [comment]
Sie befinden sich alle in der Mitte des ersten Raumes. Alle aufeinander.

**Comment by VolkanKutlar** [comment]
Die Mitte des ersten Raumes hat die Koordinate (0|0) :/
